//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework_DB_First_CRUD
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeDetail
    {
        public int EmployeeDetailId { get; set; }
        public Nullable<int> Salary { get; set; }
        public string Department { get; set; }
        public string JobType { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<int> EmpSeq { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
