//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework_DB_First_CRUD
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_table
    {
        public int EmployeeId { get; set; }
        public string Name { get; set; }
        public string PhoneNumber { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string Grade { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> EmpSeq { get; set; }
        public string Salary { get; set; }
        public string Department { get; set; }
        public string JobType { get; set; }
    }
}
