//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_API_Auth
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditEmp
    {
        public int ID { get; set; }
        public int EmpId { get; set; }
        public string OldFirstName { get; set; }
        public string NewFirstName { get; set; }
        public string OldLastName { get; set; }
        public string NewLastName { get; set; }
    }
}
